// source: proto/channel/channel.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var share_share_pb = require('../../share/share_pb.js');
goog.object.extend(proto, share_share_pb);
goog.exportSymbol('proto.channel.api.ChannelRequest', null, global);
goog.exportSymbol('proto.channel.api.ChannelRequest.ReqCase', null, global);
goog.exportSymbol('proto.channel.api.Data', null, global);
goog.exportSymbol('proto.channel.api.KeyAccepted', null, global);
goog.exportSymbol('proto.channel.api.ReceiveResponse', null, global);
goog.exportSymbol('proto.channel.api.ReceiveResponse.RespCase', null, global);
goog.exportSymbol('proto.channel.api.SetKey', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.channel.api.SetKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.channel.api.SetKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.channel.api.SetKey.displayName = 'proto.channel.api.SetKey';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.channel.api.Data = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.channel.api.Data, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.channel.api.Data.displayName = 'proto.channel.api.Data';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.channel.api.ChannelRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.channel.api.ChannelRequest.oneofGroups_);
};
goog.inherits(proto.channel.api.ChannelRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.channel.api.ChannelRequest.displayName = 'proto.channel.api.ChannelRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.channel.api.KeyAccepted = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.channel.api.KeyAccepted, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.channel.api.KeyAccepted.displayName = 'proto.channel.api.KeyAccepted';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.channel.api.ReceiveResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.channel.api.ReceiveResponse.oneofGroups_);
};
goog.inherits(proto.channel.api.ReceiveResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.channel.api.ReceiveResponse.displayName = 'proto.channel.api.ReceiveResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.channel.api.SetKey.prototype.toObject = function(opt_includeInstance) {
  return proto.channel.api.SetKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.channel.api.SetKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.SetKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.channel.api.SetKey}
 */
proto.channel.api.SetKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.channel.api.SetKey;
  return proto.channel.api.SetKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.channel.api.SetKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.channel.api.SetKey}
 */
proto.channel.api.SetKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.channel.api.SetKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.channel.api.SetKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.channel.api.SetKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.SetKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string key = 1;
 * @return {string}
 */
proto.channel.api.SetKey.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.channel.api.SetKey} returns this
 */
proto.channel.api.SetKey.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.channel.api.Data.prototype.toObject = function(opt_includeInstance) {
  return proto.channel.api.Data.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.channel.api.Data} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.Data.toObject = function(includeInstance, msg) {
  var f, obj = {
    srcKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    dstKey: jspb.Message.getFieldWithDefault(msg, 2, ""),
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.channel.api.Data}
 */
proto.channel.api.Data.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.channel.api.Data;
  return proto.channel.api.Data.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.channel.api.Data} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.channel.api.Data}
 */
proto.channel.api.Data.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrcKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDstKey(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.channel.api.Data.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.channel.api.Data.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.channel.api.Data} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.Data.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSrcKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDstKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string src_key = 1;
 * @return {string}
 */
proto.channel.api.Data.prototype.getSrcKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.channel.api.Data} returns this
 */
proto.channel.api.Data.prototype.setSrcKey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string dst_key = 2;
 * @return {string}
 */
proto.channel.api.Data.prototype.getDstKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.channel.api.Data} returns this
 */
proto.channel.api.Data.prototype.setDstKey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes data = 3;
 * @return {!(string|Uint8Array)}
 */
proto.channel.api.Data.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes data = 3;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.channel.api.Data.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.channel.api.Data.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.channel.api.Data} returns this
 */
proto.channel.api.Data.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.channel.api.ChannelRequest.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.channel.api.ChannelRequest.ReqCase = {
  REQ_NOT_SET: 0,
  SET_KEY: 1,
  DATA: 2
};

/**
 * @return {proto.channel.api.ChannelRequest.ReqCase}
 */
proto.channel.api.ChannelRequest.prototype.getReqCase = function() {
  return /** @type {proto.channel.api.ChannelRequest.ReqCase} */(jspb.Message.computeOneofCase(this, proto.channel.api.ChannelRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.channel.api.ChannelRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.channel.api.ChannelRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.channel.api.ChannelRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.ChannelRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    setKey: (f = msg.getSetKey()) && proto.channel.api.SetKey.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.channel.api.Data.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.channel.api.ChannelRequest}
 */
proto.channel.api.ChannelRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.channel.api.ChannelRequest;
  return proto.channel.api.ChannelRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.channel.api.ChannelRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.channel.api.ChannelRequest}
 */
proto.channel.api.ChannelRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.channel.api.SetKey;
      reader.readMessage(value,proto.channel.api.SetKey.deserializeBinaryFromReader);
      msg.setSetKey(value);
      break;
    case 2:
      var value = new proto.channel.api.Data;
      reader.readMessage(value,proto.channel.api.Data.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.channel.api.ChannelRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.channel.api.ChannelRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.channel.api.ChannelRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.ChannelRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSetKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.channel.api.SetKey.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.channel.api.Data.serializeBinaryToWriter
    );
  }
};


/**
 * optional SetKey set_key = 1;
 * @return {?proto.channel.api.SetKey}
 */
proto.channel.api.ChannelRequest.prototype.getSetKey = function() {
  return /** @type{?proto.channel.api.SetKey} */ (
    jspb.Message.getWrapperField(this, proto.channel.api.SetKey, 1));
};


/**
 * @param {?proto.channel.api.SetKey|undefined} value
 * @return {!proto.channel.api.ChannelRequest} returns this
*/
proto.channel.api.ChannelRequest.prototype.setSetKey = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.channel.api.ChannelRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.channel.api.ChannelRequest} returns this
 */
proto.channel.api.ChannelRequest.prototype.clearSetKey = function() {
  return this.setSetKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.channel.api.ChannelRequest.prototype.hasSetKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Data data = 2;
 * @return {?proto.channel.api.Data}
 */
proto.channel.api.ChannelRequest.prototype.getData = function() {
  return /** @type{?proto.channel.api.Data} */ (
    jspb.Message.getWrapperField(this, proto.channel.api.Data, 2));
};


/**
 * @param {?proto.channel.api.Data|undefined} value
 * @return {!proto.channel.api.ChannelRequest} returns this
*/
proto.channel.api.ChannelRequest.prototype.setData = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.channel.api.ChannelRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.channel.api.ChannelRequest} returns this
 */
proto.channel.api.ChannelRequest.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.channel.api.ChannelRequest.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.channel.api.KeyAccepted.prototype.toObject = function(opt_includeInstance) {
  return proto.channel.api.KeyAccepted.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.channel.api.KeyAccepted} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.KeyAccepted.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.channel.api.KeyAccepted}
 */
proto.channel.api.KeyAccepted.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.channel.api.KeyAccepted;
  return proto.channel.api.KeyAccepted.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.channel.api.KeyAccepted} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.channel.api.KeyAccepted}
 */
proto.channel.api.KeyAccepted.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.channel.api.KeyAccepted.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.channel.api.KeyAccepted.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.channel.api.KeyAccepted} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.KeyAccepted.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.channel.api.ReceiveResponse.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.channel.api.ReceiveResponse.RespCase = {
  RESP_NOT_SET: 0,
  KEY_ACCEPTED: 1,
  DATA: 2
};

/**
 * @return {proto.channel.api.ReceiveResponse.RespCase}
 */
proto.channel.api.ReceiveResponse.prototype.getRespCase = function() {
  return /** @type {proto.channel.api.ReceiveResponse.RespCase} */(jspb.Message.computeOneofCase(this, proto.channel.api.ReceiveResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.channel.api.ReceiveResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.channel.api.ReceiveResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.channel.api.ReceiveResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.ReceiveResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    keyAccepted: (f = msg.getKeyAccepted()) && proto.channel.api.KeyAccepted.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.channel.api.Data.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.channel.api.ReceiveResponse}
 */
proto.channel.api.ReceiveResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.channel.api.ReceiveResponse;
  return proto.channel.api.ReceiveResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.channel.api.ReceiveResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.channel.api.ReceiveResponse}
 */
proto.channel.api.ReceiveResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.channel.api.KeyAccepted;
      reader.readMessage(value,proto.channel.api.KeyAccepted.deserializeBinaryFromReader);
      msg.setKeyAccepted(value);
      break;
    case 2:
      var value = new proto.channel.api.Data;
      reader.readMessage(value,proto.channel.api.Data.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.channel.api.ReceiveResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.channel.api.ReceiveResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.channel.api.ReceiveResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.channel.api.ReceiveResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeyAccepted();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.channel.api.KeyAccepted.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.channel.api.Data.serializeBinaryToWriter
    );
  }
};


/**
 * optional KeyAccepted key_accepted = 1;
 * @return {?proto.channel.api.KeyAccepted}
 */
proto.channel.api.ReceiveResponse.prototype.getKeyAccepted = function() {
  return /** @type{?proto.channel.api.KeyAccepted} */ (
    jspb.Message.getWrapperField(this, proto.channel.api.KeyAccepted, 1));
};


/**
 * @param {?proto.channel.api.KeyAccepted|undefined} value
 * @return {!proto.channel.api.ReceiveResponse} returns this
*/
proto.channel.api.ReceiveResponse.prototype.setKeyAccepted = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.channel.api.ReceiveResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.channel.api.ReceiveResponse} returns this
 */
proto.channel.api.ReceiveResponse.prototype.clearKeyAccepted = function() {
  return this.setKeyAccepted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.channel.api.ReceiveResponse.prototype.hasKeyAccepted = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Data data = 2;
 * @return {?proto.channel.api.Data}
 */
proto.channel.api.ReceiveResponse.prototype.getData = function() {
  return /** @type{?proto.channel.api.Data} */ (
    jspb.Message.getWrapperField(this, proto.channel.api.Data, 2));
};


/**
 * @param {?proto.channel.api.Data|undefined} value
 * @return {!proto.channel.api.ReceiveResponse} returns this
*/
proto.channel.api.ReceiveResponse.prototype.setData = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.channel.api.ReceiveResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.channel.api.ReceiveResponse} returns this
 */
proto.channel.api.ReceiveResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.channel.api.ReceiveResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.channel.api);
